import "dotenv/config";
import { PrismaClient } from "@/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import { normalizeBusinessName } from "@/lib/discovery/dedup";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding local dev data...");

  // A couple of freshly-discovered Prospects, still at "new" status.
  const prospect1 = await prisma.prospect.upsert({
    where: { id: "seed-prospect-1" },
    update: {},
    create: {
      id: "seed-prospect-1",
      businessName: "Riverside Plumbing Co.",
      normalizedBusinessName: normalizeBusinessName("Riverside Plumbing Co."),
      category: "plumber",
      phone: "+15555550101",
      normalizedPhone: "+15555550101",
      email: "owner@riversideplumbing.example",
      address: "123 River Rd",
      city: "Austin",
      state: "TX",
      status: "new",
      source: "google_places",
    },
  });

  const prospect2 = await prisma.prospect.upsert({
    where: { id: "seed-prospect-2" },
    update: {},
    create: {
      id: "seed-prospect-2",
      businessName: "Sunrise Nail Salon",
      normalizedBusinessName: normalizeBusinessName("Sunrise Nail Salon"),
      category: "salon",
      phone: "+15555550102",
      normalizedPhone: "+15555550102",
      address: "456 Main St",
      city: "Austin",
      state: "TX",
      status: "previewed",
      source: "google_places",
    },
  });

  // A Prospect that already has a preview site generated + an active outreach sequence.
  await prisma.site.upsert({
    where: { id: "seed-site-1" },
    update: {},
    create: {
      id: "seed-site-1",
      prospectId: prospect2.id,
      slug: "sunrise-nail-salon",
      subdomain: "sunrise-nail-salon",
      status: "preview",
      templateId: "salon-default",
      colorScheme: { primary: "#be185d", secondary: "#fdf2f8", accent: "#f5d0c5" },
      generatedAt: new Date(),
      pages: {
        create: [
          {
            pageType: "home",
            content: {
              headline: "Sunrise Nail Salon — Relax, Refresh, Renew",
              subheadline: "Austin's cozy spot for nails done right.",
              body: "Seed placeholder copy for local dev. Real copy is generated by OpenAI (Task 4) once GOOGLE_PLACES/OPENAI keys are configured.",
              ctaLabel: "Book an appointment",
            },
          },
          {
            pageType: "about",
            content: {
              headline: "About Sunrise Nail Salon",
              body: "Seed placeholder About copy for local dev.",
              highlights: ["Locally owned", "Experienced technicians", "Relaxing atmosphere"],
            },
          },
          {
            pageType: "services",
            content: {
              headline: "Our Services",
              intro: "Seed placeholder services intro.",
              services: [
                { name: "Manicure", description: "Classic manicure with polish of your choice." },
                { name: "Pedicure", description: "Relaxing pedicure with foot soak." },
                { name: "Gel Nails", description: "Long-lasting gel nail application." },
              ],
            },
          },
          {
            pageType: "contact",
            content: {
              headline: "Get In Touch",
              body: "Seed placeholder contact copy for local dev.",
              formLabel: "Send message",
            },
          },
        ],
      },
    },
  });

  await prisma.outreachState.upsert({
    where: { prospectId: prospect2.id },
    update: {},
    create: {
      prospectId: prospect2.id,
      sequence: "initial_email_seq",
      currentStep: 1,
      status: "active",
      nextActionAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2),
    },
  });

  // A fully claimed Tenant with a published site + a staff login for local testing.
  const tenant = await prisma.tenant.upsert({
    where: { id: "seed-tenant-1" },
    update: {},
    create: {
      id: "seed-tenant-1",
      businessName: "Hilltop Auto Repair",
      normalizedBusinessName: normalizeBusinessName("Hilltop Auto Repair"),
      // Fake Retell resource ids — this Tenant is seeded as if its AI
      // receptionist has already been provisioned (Task 8), so the
      // dashboard's call-log view has something to show without needing
      // a real Retell account in local dev.
      retellLlmId: "llm_seed_dev_placeholder",
      retellAgentId: "agent_seed_dev_placeholder",
      receptionistPhoneNumber: "+15555550199",
      createdAt: new Date(),
    },
  });

  await prisma.receptionistConfig.upsert({
    where: { tenantId: tenant.id },
    update: {},
    create: {
      tenantId: tenant.id,
      businessHours: { mon: "8am-6pm", tue: "8am-6pm", wed: "8am-6pm", thu: "8am-6pm", fri: "8am-5pm" },
      faqs: [
        { question: "Do you do same-day oil changes?", answer: "Yes, usually within an hour if we're not booked up." },
      ],
      greeting: "Thanks for calling Hilltop Auto Repair, how can I help you today?",
    },
  });

  await prisma.site.upsert({
    where: { id: "seed-site-2" },
    update: {},
    create: {
      id: "seed-site-2",
      tenantId: tenant.id,
      slug: "hilltop-auto-repair",
      subdomain: "hilltop-auto-repair",
      status: "published",
      templateId: "auto-shop-default",
      generatedAt: new Date(),
      publishedAt: new Date(),
    },
  });

  await prisma.subscription.upsert({
    where: { tenantId: tenant.id },
    update: {},
    create: {
      tenantId: tenant.id,
      stripeSubscriptionId: "sub_seed_dev_placeholder",
      planId: "starter-monthly",
      status: "active",
      currentPeriodEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    },
  });

  const passwordHash = await bcrypt.hash("password123", 10);
  await prisma.tenantUser.upsert({
    where: { email: "owner@hilltopauto.example" },
    update: {},
    create: {
      tenantId: tenant.id,
      email: "owner@hilltopauto.example",
      passwordHash,
      role: "owner",
    },
  });

  await prisma.lead.createMany({
    data: [
      {
        tenantId: tenant.id,
        source: "contact_form",
        name: "Jamie Rivera",
        phone: "+15555550110",
        message: "Need an oil change quote for a 2018 Civic.",
      },
      {
        tenantId: tenant.id,
        source: "inbound_call",
        name: "Chris Nguyen",
        phone: "+15555550120",
        message: "Appointment request — Wants: brake inspection, Preferred time: this Saturday morning",
      },
    ],
    skipDuplicates: true,
  });

  // A sample completed inbound call, so the (Task 8/9) call log view has
  // something to render in local dev.
  await prisma.call.upsert({
    where: { providerCallId: "call_seed_dev_placeholder" },
    update: {},
    create: {
      direction: "inbound",
      tenantId: tenant.id,
      providerCallId: "call_seed_dev_placeholder",
      transcript:
        "Agent: Thanks for calling Hilltop Auto Repair, how can I help you today?\nUser: Hi, I'd like to book a brake inspection for this Saturday morning.\nAgent: Great, I've passed along your appointment request.",
      outcome: "appointment_requested",
      durationSec: 42,
    },
  });

  // A platform operator account for the admin/discovery views.
  const operatorPasswordHash = await bcrypt.hash("operator123", 10);
  await prisma.operatorUser.upsert({
    where: { email: "operator@localpilot.example" },
    update: {},
    create: {
      email: "operator@localpilot.example",
      passwordHash: operatorPasswordHash,
    },
  });

  console.log("Seed complete:");
  console.log(`  Prospects: ${prospect1.businessName}, ${prospect2.businessName}`);
  console.log(`  Tenant: ${tenant.businessName} (login: owner@hilltopauto.example / password123)`);
  console.log(`  Operator login: operator@localpilot.example / operator123`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
